Resources:
  ApiGatewayMethodPingGet:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      ResourceId:
        "Ref": "ApiGatewayResourcePing"  
      RestApiId:
        "Ref": "ApiGatewayRestApi"
      ApiKeyRequired: false
      Integration:
          "Type": "MOCK"
          IntegrationResponses:
            - 
              "StatusCode": "200"
              ResponseTemplates:
                "application/json": "{}"
          "PassthroughBehavior": "WHEN_NO_MATCH"
          RequestTemplates:
            "application/json": '{ "statusCode": 200 }'
      MethodResponses:
          -
            "StatusCode": "200"
            ResponseModels:
              "application/json": "Empty"